grasshopper/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from grasshopper.database import Column, Model, SurrogatePK, db, reference_col, relationship
from grasshopper.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    full_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)
    card_number = Column(db.String(20), nullable=True)
    expiration = Column(db.String(10), nullable=True)
    cvc = Column(db.String(6), nullable=True)
    address_line1 = Column(db.String(30), nullable=True)
    address_line2 = Column(db.String(30), nullable=True)
    address_zip = Column(db.String(6), nullable=True)
    address_city = Column(db.String(45), nullable=True)
    address_state = Column(db.String(15), nullable=True)
    address_country = Column(db.String(30), nullable=True)
    date_of_birth = Column(db.String(30), nullable=True)
    phone = Column(db.String(15), nullable=True)
    gender = Column(db.String(15), nullable=True)


    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    #@property
    #def full_name(self):
    #    """Full user name."""
    #    return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

class Flight(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'flights'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    full_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)
    card_number = Column(db.String(20), nullable=True)
    expiration = Column(db.String(10), nullable=True)
    cvc = Column(db.String(6), nullable=True)
    address_line1 = Column(db.String(30), nullable=True)
    address_line2 = Column(db.String(30), nullable=True)
    address_zip = Column(db.String(6), nullable=True)
    address_city = Column(db.String(45), nullable=True)
    address_state = Column(db.String(15), nullable=True)
    address_country = Column(db.String(30), nullable=True)
    date_of_birth = Column(db.String(30), nullable=True)
    phone = Column(db.String(15), nullable=True)
    gender = Column(db.String(15), nullable=True)


    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    #@property
    #def full_name(self):
    #    """Full user name."""
    #    return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

grasshopper/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import Form
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(Form):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate() 
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False
        return True



class CreditcardForm(Form):
    """Creditcard form."""

    number = StringField('Credit Card Number',
                           validators=[DataRequired(), Length(min=3, max=25)])
    expiry = StringField('Credit Card Expiration',
                        validators=[DataRequired(), Length(min=2, max=40)])
    cvc = StringField('Credit Card CVC',
                             validators=[DataRequired(), Length(min=2, max=40)])
    address_zip = StringField('Credit Card Zip Code',
                             validators=[DataRequired(), Length(min=2, max=40)])
    address_line1 = StringField('Address Line 1',
                             validators=[DataRequired(), Length(min=2, max=100)])
    address_line2 = StringField('Address Line 2', validators=[])
    address_city = StringField('City',
                             validators=[DataRequired(), Length(min=2, max=40)])
    address_state = StringField('State',
                             validators=[DataRequired(), Length(min=1, max=40)])
    address_country= StringField('Country',
                             validators=[DataRequired(), Length(min=2, max=40)])
    date_of_birth = StringField('Date of Birth',
                             validators=[DataRequired(), Length(min=2, max=40)])
    full_name = StringField('Full Name',
                             validators=[DataRequired(), Length(min=2, max=40)])
    phone = StringField('Phone Number',
                             validators=[DataRequired(), Length(min=2, max=40)])


    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(CreditcardForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(CreditcardForm, self).validate()
        if not initial_validation:
            return False

        return True

grasshopper/__init__.py
"""Main application package."""

grasshopper/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template, g
import public, user
from assets import assets
from extensions import bcrypt, cache, db, debug_toolbar, login_manager, migrate
from settings import ProdConfig

from flask.ext.sqlalchemy import SQLAlchemy
import os
import psycopg2
import urlparse


app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://localhost/users'
#'postgres://hkwdxzsksohoae:mi4SH7b8_4fB4RhENknqsDj-A3@ec2-54-83-198-111.compute-1.amazonaws.com:5432/de336vejtlpkej'
db = SQLAlchemy(app)
"""
#urlparse.uses_netloc.append("postgres")
#url = urlparse.urlparse(os.environ["DATABASE_URL"])

conn = psycopg2.connect(
    database='de336vejtlpkej',
    user='hkwdxzsksohoae',
    password='mi4SH7b8_4fB4RhENknqsDj-A3',
    host='ec2-54-83-198-111.compute-1.amazonaws.com',
    port=5432
)
"""
def create_app(config_object=ProdConfig):
    """An application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    return None


def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

grasshopper/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

grasshopper/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, request, redirect, url_for, g, flash
from flask_login import login_required, LoginManager
from grasshopper.extensions import login_manager
from grasshopper.user.forms import CreditcardForm
from grasshopper.user.models import User
from grasshopper.utils import flash_errors

from foo import X

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')

@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    return User.get_by_id(int(user_id))

@blueprint.route('/')
def jumbo():
    """Flight start page."""
    return render_template('users/testingjumbotron.html')

@blueprint.route('/members')
def members():
    """members page."""
    return render_template('users/members.html')

@blueprint.route('/testing')
def tst():
    """members page."""
    return render_template('users/testing2.html')


@blueprint.route('/flights')
def flights():
    """Flights select page."""
    return render_template('users/flights.html')

@blueprint.route('/settings', methods=['GET', 'POST'])
def settings():
    """Personal settings page."""

    form = CreditcardForm(request.form, csrf_enabled=False)
    if request.method == 'POST':
        if form.validate_on_submit():
            User.update(load_user(X), commit=True, card_number=form.number.data, expiration=form.expiry.data, cvc=form.cvc.data, address_line1=form.address_line1.data, address_line2=form.address_line2.data, address_zip=form.address_zip.data, address_city=form.address_city.data, address_state=form.address_state.data, address_country=form.address_country.data, date_of_birth=form.date_of_birth.data, phone=form.phone.data, full_name=form.full_name.data, active=True) # full_name=form.full_name.data
            return redirect(url_for('user.summary'))
        else:
            print "error"
            flash_errors(form)
            #flash('Invalid password provided', 'error')
    return render_template('users/settings.html', form=form)

@blueprint.route('/summary')
def summary():
    """members page."""
    return render_template('users/summary.html')

grasshopper/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

grasshopper/templates/footer.html
<footer>
  <small style="color:blue;">
      <ul class="company">
        <li>© Andrew Goldstein</li>
      </ul>
       
      <ul class="footer-nav">
        <li><a href="{{ url_for('public.about') }}">About</a></li>
        <li><a href="mailto:flyer.weekend@gmail.com">Contact</a></li>
      </ul>
  </small>
</footer>

grasshopper/templates/layout.html
<!DOCTYPE html>
<html lang="en" >

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Weekend Flyer</title>
    <link href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/shift.css" rel="stylesheet">
    <link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/bootstrap.css">
    <link rel="stylesheet" href="static/css/the_css.css">

    <!--<link rel="stylesheet" href="{{ url_for('static', filename='libs/bootstrap/css/bootstrap.min.css') }}">-->
    {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    {% block css %}{% endblock %}
    <!-- Bootstrap core CSS -->
    <!--<link href="static/bootstrap/css/bootstrap.min.css" rel="stylesheet">-->
    <!-- Custom styles for this template -->
    <!--<link href="static/css/jumbotron_narrow.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="static/css/accordion_demo.css">-->

    <!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
    <script type="text/javascript" src="static/js/airport_list.js"></script>
    <script type="text/javascript" src="static/js/flight_list.js"></script>
    <script type="text/javascript" src="static/js/javascript_commons.js"></script>
    <meta name="google-signin-client_id" content="552278765316-h7q89rqnrpe9ro728nrk0d2hhe4lih1s.apps.googleusercontent.com">
    <script type="text/javascript" src="static/js/creditcard.js"></script>
    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/intlTelInput.js"></script>
    <script src="static/js/usa_zipcodes.js"></script>
    <!--<script src="static/js/combodate.js"></script>-->
    <!--<link rel="stylesheet" href="static/css/stateface.css">-->
    <link rel="stylesheet" href="static/css/intlTelInput.css">
    <link rel="stylesheet" href="static/css/telephone_demo.css">
    <!--<script type='text/javascript' src="//wurfl.io/wurfl.js">-->
    </script>
  
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!--<script type="text/javascript" src="https://cdn.emailjs.com/dist/email.min.js"></script>
    <script type="text/javascript">
       (function(){
          emailjs.init("user_P9ZRzstNVrsKAxg5cttib");
       })();
    </script>-->

  </head>


    

     
  <body style="margin-top:0px; margin-left:0px; margin-right:0px; padding-top:0px; ">
    
<div class="nav" style="background-color:#303030; font-color:white;">
      <div class="containera" style="margin-left:10%; margin-right:10%; ">

    {% if current_user and current_user.is_authenticated %}

        <ul class="pull-left">
          <li><a style="text-decoration: none" href="{{ url_for('user.jumbo') }}">Weekend Flyer</a></li>
        </ul>
        <ul class="pull-right">
          <li><a style="color:white;text-decoration: none" href="{{ url_for('user.settings') }}">Settings</a></li>
        </ul>


    {% elif form %}
        <ul class="pull-left">
          <li><a style="text-decoration: none" href="#">Weekend Flyer</a></li>
        </ul>
      <ul class="pull-right">
        <li><a style="text-decoration: none" href="{{ url_for('public.register') }}">Sign up</a></li>
      </ul>
      <center><form id="loginForm" method="POST" class="navbar-form form-inline" action="/" role="login">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.username(placeholder="Username", class_="form-control") }}
          {{ form.password(placeholder="Password", class_="form-control") }}
        </div>
        <button type="submit" class="btn btn-default">Log in</button>
      </form></center>

{% endif %} 

      </div>
    </div>






        {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
           {{message}}
          </div><!-- end .alert -->
          {% endfor %}
        </div><!-- end col-md -->
      </div><!-- end row -->
          {% endif %}
      {% endwith %}



      {% block content %}{% endblock %}




      <footer class="footer" style="background: url(static/img/runway3c.jpg) no-repeat center; height:80px;">
        <small>

          <ul class="company">
            <li> &copy; 2015 Weekend Flyer, Inc.</li>
          </ul>

          <ul class="footer-nav">
            <li><a href="{{ url_for('public.about') }}">About    </a></li>
            <li><a href="mailto:flyer.weekend@gmail.com">Contact</a></li>
            <li><a href="{{ url_for('public.logout') }}">Sign Out</a></li>    
          </ul>
        </small>
      </footer>


    <!-- JavaScript at the bottom for fast page loading -->
    {% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {% block js %}{% endblock %}
  
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
  <!-- end scripts -->

  </body>
</html>

grasshopper/templates/layoutold.html
<!DOCTYPE html>
<html lang="en" >

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Weekend Flyer</title>

    <!--<link rel="stylesheet" href="{{ url_for('static', filename='libs/bootstrap/css/bootstrap.min.css') }}">-->
    {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    {% block css %}{% endblock %}

    <!-- Bootstrap core CSS -->
    <!--<link href="static/bootstrap/css/bootstrap.min.css" rel="stylesheet">-->
    <!-- Custom styles for this template -->
    <!--<link href="static/css/jumbotron_narrow.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="static/css/accordion_demo.css">-->

    <!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
    <script type="text/javascript" src="static/js/airport_list.js"></script>
    <script type="text/javascript" src="static/js/flight_list.js"></script>
    <script type="text/javascript" src="static/js/javascript_commons.js"></script>
    <meta name="google-signin-client_id" content="552278765316-h7q89rqnrpe9ro728nrk0d2hhe4lih1s.apps.googleusercontent.com">
    <script type="text/javascript" src="static/js/creditcard.js"></script>
    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/intlTelInput.js"></script>
    <script src="static/js/usa_zipcodes.js"></script>
    <!--<script src="static/js/combodate.js"></script>-->
    <!--<link rel="stylesheet" href="static/css/stateface.css">-->
    <link rel="stylesheet" href="static/css/intlTelInput.css">
    <link rel="stylesheet" href="static/css/telephone_demo.css">
    <!--<script type='text/javascript' src="//wurfl.io/wurfl.js">-->
    </script>
  
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!--<script type="text/javascript" src="https://cdn.emailjs.com/dist/email.min.js"></script>
    <script type="text/javascript">
       (function(){
          emailjs.init("user_P9ZRzstNVrsKAxg5cttib");
       })();
    </script>-->

  </head>


  <!--<body style="background:lightblue;">-->
  <body >
    <div style="background: url(static/img/runway3b.jpg) no-repeat center top; position:relative; max-height:10%; padding:0;
      margin:0;">


    <div class="container" style="position:relative;">





      <div class="header clearfix" style="align:center;" >
        <nav>
        
          {% if current_user and current_user.is_authenticated %}
          <ul class="nav nav-pills pull-right">
              <a href="{{ url_for('user.settings') }}">
                <button type="button" class="btn btn-primary btn-xlg">
                  <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                </button>
              </a>
          </ul>
          {% else %}
          <ul class="nav nav-pills pull-right">
          </ul>
          {% endif %}

        </nav>
        {% if current_user and current_user.is_authenticated %}
        <h3 class="text-muted"><a style="color:black;" href="{{ url_for('user.jumbo') }}">Weekend Flyer</a></h3>
        {% else %}
        <h3 class="text-muted"><a style="color:black;" href="{{ url_for('public.home') }}">Weekend Flyer</a></h3>
        <!--text-decoration: none"-->
        {% endif %}
      </div>

      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
           {{message}}
          </div><!-- end .alert -->
          {% endfor %}
        </div><!-- end col-md -->
      </div><!-- end row -->
          {% endif %}
      {% endwith %}

      {% block content %}{% endblock %}
   


      <footer class="footer">
        <small>

          <ul class="company">
            <li> &copy; 2015 Weekend Flyer, Inc.</li>
          </ul>

          <ul class="footer-nav">
            <li><a href="{{ url_for('public.about') }}">About    </a></li>
            <li><a href="mailto:flyer.weekend@gmail.com">Contact</a></li>
            <li><a class="fa fa-sign-out" href="{{ url_for('public.logout') }}">Sign Out</a></li>    
          </ul>
        </small>
      </footer>

    </div> <!-- /container -->

    </div>
    <!-- JavaScript at the bottom for fast page loading -->
    {% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {% block js %}{% endblock %}
  
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
  <!-- end scripts -->

  </body>
</html>

grasshopper/templates/nav.html
{% if current_user and current_user.is_authenticated %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="nav">
      <div class="containera" style="margin-left:10%; margin-right:10%;">
        <ul class="pull-left">
          <li><a href="#">Weekend Flyer</a></li>
        </ul>
        <ul class="pull-right">
          <li><a href="{{ url_for('public.register') }}">Settings</a></li>
        </ul>
      </div>
    </div>
  </div><!-- /.container -->
</nav>
    <!--<ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.jumbo') }}">Logged in as {{ current_user.username }}</a></p>
        </li>
    </ul>
        <p line-height= ".1em"> </p>-->

{% elif form %}

  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">

    <!-- Brand and toggle get grouped for better mobile display -->
    <!--<div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('public.home') }}">

        Grass Hopper

      </a>
    </div>-->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">


      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ url_for('public.register') }}">Sign up</a></li>
      </ul>
      <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.username(placeholder="Username", class_="form-control") }}
          {{ form.password(placeholder="Password", class_="form-control") }}
        </div>
        <button type="submit" class="btn btn-default">Log in</button>
      </form>

    </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>
{% endif %}